### ISSUE TITLE
Brew Tap throws exception

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/xappium.uitest#11]
# Description

Brew oddly is writing to the Error output when tapping a new cask... I may need a keg for this one...

```
Tapped 1 cask and 1 formula (31 files, 1.6MB).
   at Xappium.Tools.Brew.ExecuteInternal(Action`1 configure, CancellationToken cancellationToken) in /_/src/Xappium.Cli/Tools/Brew.cs:line 70
   at Xappium.Tools.Brew.InstallAppleSimUtils(CancellationToken cancellationToken) in /_/src/Xappium.Cli/Tools/Brew.cs:line 34
   at Xunit.Record.ExceptionAsync(Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.core\Record.cs:line 77
  Stack Trace:
     at Xappium.Cli.Tests.Tools.BrewTests.InstallsAppleSimUtils() in /_/tests/Xappium.Cli.Tests/Tests/Tools/BrewTests.cs:line 21
```

**Comment by dansiegel** [comment]
the only way to eliminate Brew from not returning an exit code of 1 after tapping a keg is to run:

```bash
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
brew update
```

Since these are very expensive and time consuming tasks.. this isn't really something that the tool should do. If someone wants to do it, a `brew-update.sh` has been added to the base of the repo.
